live_config_reload = true

[colors.bright]
black = "#404040"
blue = "#4040ff"
cyan = "#40ffff"
green = "#40ff40"
magenta = "#ff40ff"
red = "#ff4040"
white = "#dfdfdf"
yellow = "#ffff40"

[colors.dim]
black = "#202020"
blue = "#0000bf"
cyan = "#00bfbf"
green = "#00bf00"
magenta = "#bf00bf"
red = "#bf0000"
white = "#bfbfbf"
yellow = "#bfbf00"

[colors.normal]
black = "#000000"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "source code pro"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = false

[shell]
args = ["--login", "-c", "zellij -l twist"]
program = "/bin/bash"

[window.dimensions]
columns = 128
lines = 64
