theme = "snail"

[editor]
true-color = true
middle-click-paste = true
auto-pairs = false

[editor.soft-wrap]
enable = true
max-wrap = 0 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = "↪"  # set wrap-indicator to "" to hide it

[editor.lsp]
display-inlay-hints = true

[editor.gutters]

[keys.normal]
g = { o = "jump_backward" }
L = ":toggle lsp.display-inlay-hints"

