
#code

"attribute" = "#ffff00"
"type" = "#0000ff"
"type.builtin" = "#899aff"
"type.enum" = "#6d00ff"
"type.enum.variant" = "#8d00fc"
"constructor" = "#ff00b2"
"constant" = "#00ef00"
"constant.builtin" = "#00aa00"
"constant.builtin.boolean" = "#008800"
"constant.character" = "#44b853"
"constant.character.escape" = "#ffb853"
"constant.numeric" = "#008300"
"constant.numeric.integer" = "#00ff00"
"constant.numeric.float" = "#c48330"
"string" = "#44b800"
"comment" = "#4f4f4f"
"variable" = "#9ca0f0"
"label" = "#ff00ff"
"punctuation" = { fg = "#ffff74", modifiers = ["bold"] }
"punctuation.delimiter" = { fg = "#ffff74", modifiers = ["bold"] }
"punctuation.bracket" = { fg = "#ffe584", modifiers = ["bold"] }
"keyword" = "#006699"
"operator" = "#887700"
"function" = "#ff9b00"
"function.macro" = "#cfcf00"
"tag" = "#ff6060"
"namespace" = "#ff6060"
"special" = "#ffffff"
"markup" = "#ffffff"
"diff" = "#ffffff"
"diff.plus" = "#00fd00"
"diff.minus" = "#fd0000"
"diff.delta" = "#aaab00"
"diff.delta.moved" = "00ab8f"
"ui.statusline" = { fg = "foreground", bg = "background_dark" }

#interface

"ui.background"	= { bg = "#000000", fg = "#888888" }
# "ui.background.separator" = "#ffffff"
# "ui.cursor" = "#ffffff"
# "ui.cursor.normal" = "#ffffff"
# "ui.cursor.insert" = "#ffffff"
# "ui.cursor.select" = "#ffffff"
# "ui.cursor.match" = "#ffffff"
# "ui.cursor.primary" = "#ffffff"
# "ui.cursor.primary.normal" = "#ffffff"
# "ui.cursor.primary.insert" = "#ffffff"
# "ui.cursor.primary.select" = "#ffffff"
# "ui.debug.breakpoint" = "#ffffff"
# "ui.debug.active" = "#ffffff"
# "ui.gutter" = "#111210"
# "ui.gutter.selected" = "#ffffff"
# "ui.highlight.frameline" = "#ffffff"
# "ui.linenr" = "#ffffff"
# "ui.linenr.selected" = "#ffffff"
# "ui.statusline" = "#ffffff"
# "ui.statusline.inactive" = "#ffffff"
# "ui.statusline.normal" = "#ffffff"
# "ui.statusline.insert" = "#ffffff"
# "ui.statusline.select" = "#ffffff"
# "ui.statusline.separator" = "#ffffff"
# "ui.popup" = "#ffffff"
# "ui.popup.info" = "#ffffff"
# "ui.window" = "#ffffff"
# "ui.help" = "#ffffff"
# "ui.text" = "#ffffff"
# "ui.text.focus" = "#ffffff"
# "ui.text.inactive" = "#ffffff"
# "ui.text.info" = "#ffffff"
# "ui.virtual.ruler" = "#ffffff"
# "ui.virtual.whitespace" = "#ffffff"
# "ui.virtual.indent-guide" = "#ffffff"
# "ui.virtual.inlay-hint" = { modifiers = ["italic"] }
# "ui.virtual.inlay-hint.parameter" = "#ffffff"
# "ui.virtual.inlay-hint.type" = "#ffffff"
# "ui.virtual.wrap" = "#ffffff"
"ui.menu" = { fg = "#cccccc", modifiers = ["italic"] }
"ui.menu.selected" = { fg = "#cc00cc", modifiers =  ["italic"] }
"ui.menu.scroll" = { fg = "#cccccc", modifiers = ["italic"] }
"ui.selection" = { modifiers = ["reversed"] }
"ui.selection.primary" = { bg = "#422424", modifiers = ["reversed"] }
# "ui.highlight" = "#ffffff"
# "ui.cursorline.primary" = "#ffffff"
# "ui.cursorline.secondary" = "#ffffff"
# "ui.cursorcolumn.primary" = "#ffffff"
# "ui.cursorcolumn.secondary" = "#ffffff"
"warning" = "#ff9999"
"error" = "#fc0000"
# "info" = "#ffffff"
# "hint" = "#ffffff"
"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.error" = { underline = { style = "curl", color = "#cc0400" } }
# "diagnostic.hint" = "#ffffff"
# "diagnostic.info" = "#ffffff"
# "diagnostic.warning" = "#ffffff"
# "diagnostic.error" = "#ffffff"
[palette]
foreground = "#f8f8f2"
background_dark = "#21222c"
